import { Box, Button, Typography } from '@mui/material';
import Head from 'next/head';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';
import UndoIcon from '@mui/icons-material/Undo';
import { useRouter } from 'next/router';
import { DataComponent } from '../../utils/data-mock';
import styles from '../../styles/Home.module.css';
import { useState } from 'react';
import Image from 'next/image';

export default function ReactComponent() {
	const router = useRouter();
	const data = DataComponent;
	const [name, setName] = useState('');

  const handleNameChange = (value) => {
    setName(value);
  };
	return (
		<>
			<Box>
				<Head>
					<title>Function Component</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<Box
					sx={{
						mt: 10,
					}}
				>
					<Typography align="center" variant="h2">
						This is Function Component
					</Typography>
				</Box>
				<Typography variant="h5" sx={{ textAlign: 'center' }}>
					This is Props
				</Typography>
				<Box align="center" mt={10}>
					<Button
						variant="contained"
						color="error"
						onClick={() => {
							router.push('/class-component-react');
						}}
						sx={{
							minWidth: 200,
						}}
						endIcon={<ArrowForwardIcon />}
					>
						Class Component
					</Button>
				</Box>
				<Box align="center" mt={2}>
					<Button
						variant="contained"
						color="error"
						onClick={() => {
							router.push('/Higher-Order-Component');
						}}
						sx={{
							minWidth: 200,
						}}
						endIcon={<ArrowForwardIcon />}
					>
						Higher Order Component
					</Button>
				</Box>
				<Box align="center" mt={3} mb={3}>
					<Button
						variant="contained"
						color="primary"
						onClick={() => {
							router.push('/');
						}}
						sx={{
							minWidth: 200,
						}}
						startIcon={<UndoIcon />}
					>
						Back
					</Button>
				</Box>
				<footer className={styles.footer}>
					<a
						href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
						target="_blank"
						rel="noopener noreferrer"
					>
						Powered by{' '}
						<span className={styles.logo}>
							<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
						</span>
					</a>
				</footer>
			</Box>
		</>
	);
}
