import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import {
	Box,
	Button,
	Card,
	CardActionArea,
	CardActions,
	CardContent,
	CardMedia,
	Grid,
	Icon,
	Typography,
} from '@mui/material';
import { Data } from '../utils/data-mock';
import { useRouter } from 'next/router';
import ArrowForwardIcon from '@mui/icons-material/ArrowForward';

export default function Home() {
	const dataMock = Data;
	const router = useRouter();
	console.log('data', dataMock);
	return (
		<div className={styles.container}>
			<Head>
				<title>React Aptech</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="https://nextjs.org">React.js!</a>
				</h1>

				<p className={styles.description}>
					Get started by editing <code className={styles.code}>pages/index.js</code>
				</p>

				<div className={styles.grid}>
					{dataMock.map((item, index) => {
						return (
							<>
								<Box className={styles.card} key={item.id}>
									<h2>
										{item.title}
										<br />
									</h2>
									<p>{item.description}</p>
									<Button
										variant="contained"
										onClick={() => {
											router.push(item.link);
										}}
										sx={{ marginTop: 3 }}
										endIcon={<ArrowForwardIcon />}
									>
										Link to
									</Button>
								</Box>
							</>
						);
					})}
				</div>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
